name: Rested.Core CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  rested-core-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 'Install GitVersion'
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '5.x'
          
      - name: 'Determine Version'
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
          
      - name: 'Tag Commit'  
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ github.token }}
          custom_tag: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
          
      - name: 'Restore and Build Solution'
        uses: KhaosVoid/Rested-GitHub-Shared/actions/restore-build-solution@main
          
      - name: 'Publish NuGet Packages to GPR'
        uses: KhaosVoid/Rested-GitHub-Shared/actions/publish-nuget-packages@main
        with:
          package-version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
          repository-source-url: 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json'
          nuget-api-key: ${{ github.token }}
          
      - name: 'Publish NuGet Packages to NuGet.org'
        uses: KhaosVoid/Rested-GitHub-Shared/actions/publish-nuget-packages@main
        with:
          package-version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
          repository-source-url: 'https://api.nuget.org/v3/index.json'
          nuget-api-key: ${{ secrets.RESTED_NUGET_API_KEY }}