name: Rested.Core CD

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '**/*.md'
      - '.github/**'

jobs:
  build:
    name: Rested.Core CD
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{matrix.dotnet-version}}
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{github.token}}
    - name: Restore (Rested.Core)
      run: dotnet restore Rested.Core
    - name: Restore (Rested.Core.MSTest)
      run: dotnet restore Rested.Core.MSTest
    - name: Build (Rested.Core)
      run: dotnet build Rested.Core --configuration Release --no-restore
    - name: Build (Rested.Core.MSTest)
      run: dotnet build Rested.Core.MSTest --configuration Release --no-restore
    - name: Test (Rested.Core)
      run: dotnet test Rested.Core --no-restore --verbosity normal
    - name: Create NuGet Package (Rested.Core)
      run: dotnet pack Rested.Core --configuration Release --no-restore --version-suffix ${{github.run_number}}
    - name: Create NuGet Package (Rested.Core.MSTest)
      run: dotnet pack Rested.Core.MSTest --configuration Release --no-restore --version-suffix ${{github.run_number}}
    - name: Publish NuGet package to GitHub Package Repository (Rested.Core)
      run: dotnet nuget push ./Rested.Core/bin/Release/*.nupkg
    - name: Publish NuGet package to GitHub Package Repository (Rested.Core.MSTest)
      run: dotnet nuget push ./Rested.Core.MSTest/bin/Release/*.nupkg