name: Rested.Core CD

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    name: Rested.Core CD
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{matrix.dotnet-version}}
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{github.token}}

    # GitVersion
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    # Set NuGet Package Version Variable
    - name: Set NuGet Package Version Variable
      id: nugetPackageVersion
      run: |
        echo "version=${{steps.gitversion.outputs.major}}.${{steps.gitversion.outputs.minor}}.${{steps.gitversion.outputs.commitsSinceVersionSource}}" >> $GITHUB_OUTPUT

    # Restore
    - name: Restore (Rested.Core.Data)
      run: dotnet restore Rested.Core.Data
    - name: Restore (Rested.Core.Client)
      run: dotnet restore Rested.Core.Client
    - name: Restore (Rested.Core.MediatR)
      run: dotnet restore Rested.Core.MediatR
    - name: Restore (Rested.Core.Server)
      run: dotnet restore Rested.Core.Server
    - name: Restore (Rested.Core.MediatR.MSTest)
      run: dotnet restore Rested.Core.MediatR.MSTest
    - name: Restore (Rested.Core.Server.MSTest)
      run: dotnet restore Rested.Core.Server.MSTest
    - name: Restore (Rested.Core.Data.UnitTest)
      run: dotnet restore Rested.Core.Data.UnitTest

    # Build
    - name: Build (Rested.Core.Data)
      run: dotnet build Rested.Core.Data --configuration Release --no-restore
    - name: Build (Rested.Core.Client)
      run: dotnet build Rested.Core.Client --configuration Release --no-restore
    - name: Build (Rested.Core.MediatR)
      run: dotnet build Rested.Core.MediatR --configuration Release --no-restore
    - name: Build (Rested.Core.Server)
      run: dotnet build Rested.Core.Server --configuration Release --no-restore
    - name: Build (Rested.Core.MediatR.MSTest)
      run: dotnet build Rested.Core.MediatR.MSTest --configuration Release --no-restore
    - name: Build (Rested.Core.Server.MSTest)
      run: dotnet build Rested.Core.Server.MSTest --configuration Release --no-restore
    - name: Build (Rested.Core.Data.UnitTest)
      run: dotnet build Rested.Core.Data.UnitTest --configuration Release --no-restore

    # Test
    - name: Test (Rested.Core.Data.UnitTest)
      run: dotnet test Rested.Core.Data.UnitTest --no-restore --verbosity normal

    # Create NuGet Packages
    - name: Create NuGet Package (Rested.Core.Data)
      run: dotnet pack Rested.Core.Data --configuration Release --no-restore -p:Version${{steps.nugetPackageVersion.outputs.version}}
    - name: Create NuGet Package (Rested.Core.Client)
      run: dotnet pack Rested.Core.Client --configuration Release --no-restore -p:Version${{steps.nugetPackageVersion.outputs.version}}
    - name: Create NuGet Package (Rested.Core.MediatR)
      run: dotnet pack Rested.Core.MediatR --configuration Release --no-restore -p:Version${{steps.nugetPackageVersion.outputs.version}}
    - name: Create NuGet Package (Rested.Core.Server)
      run: dotnet pack Rested.Core.Server --configuration Release --no-restore -p:Version${{steps.nugetPackageVersion.outputs.version}}
    - name: Create NuGet Package (Rested.Core.MediatR.MSTest)
      run: dotnet pack Rested.Core.MediatR.MSTest --configuration Release --no-restore -p:Version${{steps.nugetPackageVersion.outputs.version}}
    - name: Create NuGet Package (Rested.Core.Server.MSTest)
      run: dotnet pack Rested.Core.Server.MSTest --configuration Release --no-restore -p:Version${{steps.nugetPackageVersion.outputs.version}}

    # Publish NuGet Packages
    - name: Publish NuGet Package to GitHub Package Repository (Rested.Core.Data)
      run: dotnet nuget push ./Rested.Core.Data/bin/Release/*.nupkg
    - name: Publish NuGet Package to GitHub Package Repository (Rested.Core.Client)
      run: dotnet nuget push ./Rested.Core.Client/bin/Release/*.nupkg
    - name: Publish NuGet Package to GitHub Package Repository (Rested.Core.MediatR)
      run: dotnet nuget push ./Rested.Core.MediatR/bin/Release/*.nupkg
    - name: Publish NuGet Package to GitHub Package Repository (Rested.Core.Server)
      run: dotnet nuget push ./Rested.Core.Server/bin/Release/*.nupkg
    - name: Publish NuGet Package to GitHub Package Repository (Rested.Core.MediatR.MSTest)
      run: dotnet nuget push ./Rested.Core.MediatR.MSTest/bin/Release/*.nupkg
    - name: Publish NuGet Package to GitHub Package Repository (Rested.Core.Server.MSTest)
      run: dotnet nuget push ./Rested.Core.Server.MSTest/bin/Release/*.nupkg
