name: Rested.Core CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  rested-core-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 'Install GitVersion'
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '5.x'

      - name: 'Determine Version'
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
          
      - name: 'Restore and Build Solution'
        uses: KhaosVoid/Rested-GitHub-Shared/actions/restore-build-solution@main
        
      - name: 'Run Unit Tests'
        uses: KhaosVoid/Rested-GitHub-Shared/actions/unit-test-dotnet-solution@main